import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { spawn } from "node:child_process";
import { exit } from "node:process";
import esbuildSvelte from "esbuild-svelte";
import svelteConfig from "./svelte.config.mjs";

import { watch } from "node:fs";
import { debounce } from "es-toolkit";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

process.NODE_ENV = prod ? "production" : "development";

if (!prod) {
	const triggerReload = debounce(() => {
		console.log("Detected change in build outputs. Reloading Obsidian plugin...");
		const reloadProcess = spawn(
			"obsidian",
			["plugin:reload", "id=content-addressed-attachments"],
			{
				shell: true,
				stdio: "inherit",
			},
		);
		reloadProcess.on("error", (err) => {
			console.error("Failed to reload plugin via CLI:", err);
		});
	}, 500);

	// 监听构建输出目录的产物文件变化来触发重载。
	// 相比于直接监听特定文件，监听根目录能有效应对某些构建工具或编辑器在保存文件时“先删除再重建”的写入机制，避免监听器句柄失效。
	// 这里通过防抖合并 500ms 内 esbuild 与 tailwind 同时写入所产生的多个变化事件。
	watch(".", (eventType, filename) => {
		if (filename === "main.js" || filename === "styles.css") {
			triggerReload();
		}
	});
}

await Promise.all([
	// esbuild
	(async () => {
		const context = await esbuild.context({
			banner: {
				js: banner,
			},
			plugins: [esbuildSvelte(svelteConfig)],
			entryPoints: ["src/main.ts"],
			pure: ["console.log", "console.warn", "console.debug"],
			bundle: true,
			external: [
				"obsidian",
				"electron",
				"@codemirror/autocomplete",
				"@codemirror/collab",
				"@codemirror/commands",
				"@codemirror/language",
				"@codemirror/lint",
				"@codemirror/search",
				"@codemirror/state",
				"@codemirror/view",
				"@lezer/common",
				"@lezer/highlight",
				"@lezer/lr",
				...builtinModules,
			],
			format: "cjs",
			target: "es2018",
			logLevel: "info",
			sourcemap: prod ? false : "inline",
			treeShaking: true,
			outfile: "main.js",

			minify: prod,
		});
		if (prod) {
			await context.rebuild();
		} else {
			await context.watch();
		}
	})(),
	// tailwind
	(async () => {
		return new Promise((resolve, reject) => {
			const args = [
				"-i",
				"src/main.tailwind.css",
				"-o",
				"styles.css",
				...(prod ? ["--minify"] : ["--watch"]),
			];

			console.log("Building TailwindCSS...");

			const tailwindProcess = spawn("npx", ["tailwindcss", ...args], {
				stdio: "inherit",
				shell: true,
			});

			tailwindProcess.on("close", (code) => {
				if (code === 0) {
					console.log("TailwindCSS build completed");
					resolve();
				} else {
					reject(
						new Error(`TailwindCSS build failed with code ${code}`),
					);
				}
			});

			tailwindProcess.on("error", reject);
		});
	})(),
]);
console.log("done");
if (prod) {
	exit(0);
}
