import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { spawn } from "node:child_process";
import { exit } from "node:process";
import esbuildSvelte from "esbuild-svelte";
import { sveltePreprocess } from "svelte-preprocess";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

await Promise.all([
	// esbuild
	(async () => {
		const context = await esbuild.context({
			banner: {
				js: banner,
			},
			plugins: [
				esbuildSvelte({
					compilerOptions: { css: "injected" },
					preprocess: sveltePreprocess(),
				}),
			],
			entryPoints: ["src/main.ts"],
			bundle: true,
			external: [
				"obsidian",
				"electron",
				"@codemirror/autocomplete",
				"@codemirror/collab",
				"@codemirror/commands",
				"@codemirror/language",
				"@codemirror/lint",
				"@codemirror/search",
				"@codemirror/state",
				"@codemirror/view",
				"@lezer/common",
				"@lezer/highlight",
				"@lezer/lr",
				...builtinModules,
			],
			format: "cjs",
			target: "es2018",
			logLevel: "info",
			sourcemap: prod ? false : "inline",
			treeShaking: true,
			outfile: "main.js",
			minify: prod,
		});
		if (prod) {
			await context.rebuild();
		} else {
			await context.watch();
		}
	})(),
	// tailwind
	(async () => {
		return new Promise((resolve, reject) => {
			const args = [
				"-i",
				"src/main.tailwind.css",
				"-o",
				"styles.css",
				...(prod ? ["--minify"] : ["--watch"]),
			];

			console.log("Building TailwindCSS...");

			const tailwindProcess = spawn("npx", ["tailwindcss", ...args], {
				stdio: "inherit",
				shell: true,
			});

			tailwindProcess.on("close", (code) => {
				if (code === 0) {
					console.log("TailwindCSS build completed");
					resolve();
				} else {
					reject(
						new Error(`TailwindCSS build failed with code ${code}`),
					);
				}
			});

			tailwindProcess.on("error", reject);
		});
	})(),
]);
console.log("done");
exit(0);
