// Obsidian 插件产物构建配置（rolldown-vite 8）。
// 由根目录 vite-build.mjs 以 --mode production/development 调用，
// 产物输出到仓库根目录的 main.js，供 Obsidian 加载。
import { defineConfig, transformWithOxc } from "vite";
import { builtinModules } from "node:module";
import { readFile } from "node:fs/promises";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import { compileModule } from "svelte/compiler";
import { sveltePreprocess } from "svelte-preprocess";

export default defineConfig(({ mode }) => {
	const prod = mode === "production";

	const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

	return {
		plugins: [
			svelte({
				configFile: false,
				preprocess: sveltePreprocess(),
				compilerOptions: {
					css: "injected",
					runes: true,
					// disable all warnings coming from node_modules and all accessibility warnings
					warningFilter: (warning) =>
						!warning.filename?.includes("node_modules") &&
						!warning.code.startsWith("a11y"),
				},
				experimental: {
					compileModule: {
						// vite8 下该插件拿到的 .svelte.ts 仍是未剥离 TS 的原始内容，
						// 改由下方插件全权处理：剥离类型 → 编译 runes
						exclude: [/\.svelte\.ts$/],
					},
				},
			}),
			{
				// .svelte.ts runes 模块编译：load 阶段一次完成类型剥离 + runes 编译，
				// 输出纯 JS，后续管线无需再关心该文件类型
				name: "compile-svelte-ts-modules",
				enforce: "pre",
				async load(id) {
					if (!id.endsWith(".svelte.ts")) {
						return null;
					}
					const source = await readFile(id, "utf8");
					// target 必须与产物一致：源码中的 using 声明需要在此降级为
					// try/finally，否则 svelte/compiler 的 acorn 无法解析
					const stripped = await transformWithOxc(source, id, {
						lang: "ts",
						target: "es2022",
					});
					if (stripped.errors.length > 0) {
						throw new Error(
							`TS strip failed for ${id}: ${stripped.errors
								.map(String)
								.join("; ")}`,
						);
					}
					const compiled = compileModule(stripped.code, {
						filename: id,
						generate: "client",
					});
					return { code: compiled.js.code, map: compiled.js.map };
				},
			},
		],
		build: {
			outDir: ".",
			// 产物直接写入仓库根目录，严禁清空目录（会删掉 styles.css 等非产物文件）
			emptyOutDir: false,
			lib: {
				entry: "src/main.ts",
				formats: ["cjs"],
				fileName: () => "main.js",
			},
			target: "es2022",
			minify: prod ? "oxc" : false,
			sourcemap: prod ? false : "inline",
			rollupOptions: {
				external: [
					"obsidian",
					"electron",
					/^@codemirror\//,
					/^@lezer\//,
					...builtinModules,
					...builtinModules.map((m) => `node:${m}`),
				],
				output: {
					banner,
					// 复刻 esbuild 的导出形态：module.exports.default + __esModule，
					// 避免 exports:'auto' 在单 default 导出时平铺为 module.exports=Class
					exports: "named",
				},
				treeshake: {
					// 复刻 esbuild pure: ["console.log", "console.warn", "console.debug"]：
					// 仅剥离这三个方法的生产产物调用，保留 console.error
					manualPureFunctions: prod
						? ["console.log", "console.warn", "console.debug"]
						: undefined,
				},
			},
		},
	};
});
